{
  "hash": "7610864d7ecf06bf5b803ed0ebef2894",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ICU Mortality: Interpretable Inference Meets Predictive Power\"\ndescription: \"Two models on 91,713 ICU admissions: an interpretable logistic regression for clinical inference, and a cross-validated LightGBM (AUC 0.90) for prediction, with an honest accounting of why the two AUCs differ.\"\nimage: featured.png\ndate: 2026-05-04\ncategories: [Biostatistics, Machine Learning, Clinical Risk Modeling, R]\n---\n\n## The question\n\nWhich patient characteristics and **first-day** ICU measurements are most associated with in-hospital mortality, and how much predictive performance do you trade away by insisting on a model clinicians can actually read?\n\nI answered both halves with a deliberate two-track design: an interpretable logistic regression for inference, and a gradient-boosted LightGBM for predictive performance, compared honestly on the same cohort.\n\n## Data\n\nThe WiDS Datathon 2020 (GOSSIS) cohort: 91,713 ICU admissions across 186 variables, spanning demographics, admission context, comorbidity flags, and first-day vitals and labs. Overall mortality was about 9%, a meaningful class imbalance the models had to handle.\n\nThe two tracks used the data differently, on purpose.\n\n- **Logistic track.** A parsimonious 10 predictors, complete-case (71,926 rows), every coefficient interpretable. Lactate (about 75% missing) was dropped rather than imputed on weak ground, and I ran a complete-case selection-bias check. Retained versus dropped patients had near-identical mortality (8.5% versus 9.0%), which is what makes complete-case analysis defensible here rather than convenient.\n- **LightGBM track.** 72 features including APACHE components and comorbidity flags, with no row-dropping, since gradient boosting routes missing values through its splits natively.\n\n## Method\n\n**Logistic regression** with pre-ICU length of stay log-transformed for skew. Multicollinearity was checked explicitly through a correlation heatmap (BUN and creatinine at r ≈ 0.69, as expected for two renal markers) and VIFs (all below 2.1). Effect sizes were rescaled by each predictor's interquartile range, the figure below, so they read as \"risk change across the middle 50% of patients\" instead of uninformative per-unit odds ratios clustered near 1.0.\n\n**LightGBM** tuned for binary classification with `scale_pos_weight` for the imbalance, evaluated by 5-fold stratified cross-validation, then refit on all data for a Kaggle submission pipeline (test-set categorical encoding aligned to training levels).\n\nThe IQR-scaled odds-ratio figure regenerates live from the fitted logistic coefficients, so it is fully reproducible without the raw 91k-row dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(scales)\n\n# Logistic-regression coefficients (log-odds scale) from the primary model on\n# 71,926 complete-case admissions, with each continuous predictor's IQR.\n# Reproduced from the model output for a self-contained figure.\ncoef_tbl <- tibble::tribble(\n  ~label,               ~estimate,    ~se,        ~iqr,\n  \"Age\",                 0.0175628,   0.0010024,  22,\n  \"Male gender\",         0.0957692,   0.0290655,   1,\n  \"Elective surgery\",   -1.1480364,   0.0525970,   1,\n  \"Pre-ICU LOS (log)\",   0.2935830,   0.0217234,   0.3,\n  \"Min mean BP\",        -0.0305368,   0.0010140,  20,\n  \"Min SpO2\",           -0.0279573,   0.0010242,   6,\n  \"Max resp rate\",       0.0165362,   0.0011609,   9,\n  \"Max creatinine\",      0.0022678,   0.0107270,   0.7,\n  \"Max BUN\",             0.0126412,   0.0007863,  18,\n  \"Max WBC\",             0.0409460,   0.0016919,   7.3\n) %>%\n  mutate(\n    or     = exp(estimate * iqr),\n    lo     = exp((estimate - 1.96 * se) * iqr),\n    hi     = exp((estimate + 1.96 * se) * iqr),\n    effect = if_else(or < 1, \"Protective\", \"Higher risk\")\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- ggplot(coef_tbl, aes(x = or, y = reorder(label, or), color = effect)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"grey55\") +\n  geom_errorbarh(aes(xmin = lo, xmax = hi), height = 0.25, linewidth = 0.6) +\n  geom_point(size = 3) +\n  scale_x_log10(breaks = c(0.3, 0.5, 0.75, 1, 1.25, 1.5)) +\n  scale_color_manual(values = c(\"Protective\" = \"#1F7A63\",\n                                \"Higher risk\" = \"#15433C\")) +\n  labs(x = \"Adjusted odds ratio per IQR (log scale)\", y = NULL, color = NULL) +\n  theme_minimal(base_size = 12) +\n  theme(legend.position = \"top\", panel.grid.minor = element_blank())\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `geom_errorbarh()` was deprecated in ggplot2 4.0.0.\nℹ Please use the `orientation` argument of `geom_errorbar()` instead.\n```\n\n\n:::\n\n```{.r .cell-code}\np\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`height` was translated to `width`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Adjusted odds ratios per interquartile-range increase. Points left of the dashed line are protective; points right are associated with higher mortality. Scaling by IQR makes clinical effect sizes directly comparable across predictors on different units.](index_files/figure-html/fig-or-iqr-1.png){#fig-or-iqr width=768}\n:::\n:::\n\n\n\n\n## Key results\n\n**Inference (logistic regression).** Elective surgery was the strongest protective factor. Hemodynamic and respiratory instability (lower minimum mean BP, lower minimum SpO₂) and organ-stress markers (higher WBC, BUN, respiratory rate) raised risk, and age climbed monotonically across every decile. Creatinine was non-significant, and rather than wave it off, the VIF and correlation analysis show why: shared renal variance with BUN, not clinical irrelevance.\n\n**Prediction versus inference, reported honestly.** This is the part worth dwelling on.\n\n::: {.callout-note}\n## Two AUCs, reported honestly\n\n| Model | AUC | What kind of number this is |\n|---|---|---|\n| Logistic regression | 0.784 | Apparent (in-sample), optimistic |\n| LightGBM | **0.896** | 5-fold cross-validated, realistic |\n\nLightGBM's cross-validated 0.896 (± 0.0035 across folds) genuinely beats the logistic model. But the logistic 0.784 is in-sample and therefore inflated, so the real performance gap is smaller than a naive 0.896-versus-0.784 reading suggests. Comparing a cross-validated number against an apparent one would be the kind of mistake that overstates a model, and flagging it is the point.\n:::\n\nOne caveat I would raise before a reviewer does: LightGBM's top features are APACHE's own pre-computed mortality probabilities (`apache_4a_hospital_death_prob`). So part of that 0.896 reflects the model successfully recovering an established clinical risk score already embedded in the data. That is legitimate, but worth naming rather than presenting the number bare.\n\n## Why it matters\n\nThis is the exact tension in applied clinical modeling. The interpretable model is what gets trusted, audited, and deployed at the bedside; the boosted model shows the ceiling of what is predictable. Doing both, and reporting the performance gap without inflating it, is the workflow real clinical-analytics and biostatistics teams use, and the methodological honesty is the transferable skill, more than either model alone.\n\n## Limitations\n\nStated plainly: the analysis is observational, so no causal claims. The logistic diagnostics (ROC, calibration, density separation) are apparent (in-sample); only the LightGBM AUC is cross-validated. Complete-case modeling drops about 22% of rows for the logistic track, which the bias check addresses but does not eliminate. And the 10-predictor logistic model trades discrimination for interpretability by design.\n\n## Links\n\n- 📄 [Read the full report](Wids-ICU-Kaggle.pdf) covers the complete code, all exploratory figures, both models, CV results, and the Kaggle submission pipeline\n- 💻 [Code on GitHub](https://github.com/Jonathanmuniz13/icu-mortality)\n- 🗄️ Data: [WiDS Datathon 2020 (GOSSIS)](https://www.kaggle.com/c/widsdatathon2020)\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}